services:
    web:
        image: nginx:latest
        volumes:
            - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ..:/var/www/html
        ports:
            - 80:80
        restart: always
        depends_on:
            - php
            - db
    db:
      image: postgres:14.5
      restart: always
      environment:
        - POSTGRES_DB=${DATABASE_NAME}
        - POSTGRES_USER=${DATABASE_USER}
        - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      shm_size: 1g
      ports:
        - 5432:5432
      volumes:
        - ./conf/postgres:/docker-entrypoint-initdb.d
        - db-data:/var/lib/postgresql/data
    php:
        build: conf/php
        restart: always
        volumes:
            - ./conf/php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./conf/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
            - ..:/var/www/html

volumes:
    db-data:
